# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Layout/IndentationWidth:
  Enabled: true

Layout/LineLength:
  Max: 150  # You can adjust this value to your preferred maximum line length
  Enabled: true

Style/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Style/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical
# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false
